version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  tester:
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - nginx
    volumes:
      - output:/output

volumes:
  output:
